# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
  - master
resources:
  repositories:
    - repository: library
      type: git
      name: Moviepanda/pipeline-library
      ref: refs/heads/master

pool:
  vmImage: 'ubuntu-latest'
variables:
  YARN_CACHE_FOLDER: $(Pipeline.Workspace)/.yarn

stages:
  - template: /pipeline/front-end-continuous-integration.yml@library
    parameters:
      applicationName: 'movie-reservation-admin'
      targetFolder: '/var/www/qa.admin.moviepanda.in/public_html'
      buildOutputFolder: 'dist/movie-reservation-admin'
      sshEndpoint: 'godwin'